### ISSUE TITLE
Wi-Fi (а также ряд других вопросов)

### ISSUE THREAD

**Issue by mike5555555** [murproject/mur_simulator#2]
Здравствуйте, я программирую в murIDE и у меня не находит wifi сети murIDE. Я переключал режимы, открывал и закрывал симулятор, ждал - не помогает. Возможно, я что-то не понял в документации, но там написано, подключиться к аппарату, но я не понимаю как это делать. Не могли бы вы мне помочь?

**Comment by Zauzolkov** [comment]
Приветствую.

Конкретно симулятор не имеет отношения к WiFi-сети, она создаётся реальным аппаратом, если таковой у вас имеется. Для работы в симуляторе это не требуется.

Для того, чтобы запускать программы в симуляторе, сначала необходимо в murIDE выбрать режим "Local" (кнопка становится синего цвета).

![Screenshot](https://user-images.githubusercontent.com/50130486/100084732-d8129280-2e96-11eb-931c-62ef0a6bf08a.png)

Также вы можете обратиться к [данному видеоуроку](https://www.youtube.com/watch?v=TJjmakQxz5M), где наглядно показан процесс работы с симулятором.

**Comment by mike5555555** [comment]
Спасибо за ответ. То есть, wifi нужен для подключения к материальному
аппарату, а в симуляторе нужно только запустить код в режиме local, так?

вт, 24 нояб. 2020 г., 13:59 Alex Zauzolkov <notifications@github.com>:

**Comment by Zauzolkov** [comment]
> То есть, wifi нужен для подключения к материальному аппарату, а в симуляторе нужно только запустить код в режиме local, так?

Да, всё верно.

**Comment by mike5555555** [comment]
Здравствуйте, у меня сново вопрос. В видео по регуляторам показано, что для
регуляции по курсу используются двигатели 0 и 1, однако в документации
написано, что они отвечаю за движение вперед-назад. Не могли бы вы мне
сказать, какие двигатели за что отвечают (все 5, если вам не трудно)?
Заранее огромное спасибо

вт, 24 нояб. 2020 г. в 14:29, Alex Zauzolkov <notifications@github.com>:

**Comment by Zauzolkov** [comment]
> для регуляции по курсу используются двигатели 0 и 1, однако в документации
> написано, что они отвечаю за движение вперед-назад.

На самом деле тут нет никакого противоречия. Это маршевые движители, и если подать одинаковую тягу на оба из них, то мы получим движение вперёд или назад. Если же тяга будет не одинаковой (например, только на один из них), то получится поворот. Таким образом, регулируя тягу на этих движителях можно корректировать курс. Постарался на картинке изобразить мысль:

![screenshot_marsh](https://user-images.githubusercontent.com/50130486/100397183-1628d580-3094-11eb-9d49-3260be07cef8.png)

Обозначения движителей (акутально только для **симулятора**):

![screenshot_motors](https://user-images.githubusercontent.com/50130486/100397194-22149780-3094-11eb-9bc4-57fe353e3cf2.png)

**Comment by mike5555555** [comment]
Спасибо большое

пт, 27 нояб. 2020 г., 2:43 Alex Zauzolkov <notifications@github.com>:

**Comment by mike5555555** [comment]
Здравствуйте, у меня в очередной раз возник вопрос. В видео по
распознаванию цветов показано (где бинаризация часть 6.2), что можно
отфильтровать цвета и вывести на экран в белом виде то, что соответствует
указанному диапазону. Но, вот вопрос: можно ли сделать так, чтобы робот
запомнил, какой цвет я отделил, не выводя картинку на экран, могу ли я
сохранить это значение в переменной и использовать дальше? Если да, то
какая функция из open cv2 для этого есть?

пт, 27 нояб. 2020 г. в 07:27, Alex Zauzolkov <notifications@github.com>:

**Comment by Zauzolkov** [comment]
Ваш вопрос скорее относится к OpenCV, чем к симулятору как таковому. Предлагаю обратиться к [документации по OpenCV](https://docs.opencv.org/4.1.0/) и многочисленным урокам по OpenCV и Python, которые открыто доступны в интернете.

Я всё ещё открыт для вопросов по поводу особенностей __симулятора и murIDE__ или же, если при работе с ними возникнут некие трудности.

_P.S._

_В вашем вопросе явно прослеживается задание для конкурса, так что готового примера исходного кода не будет `:)` Надеюсь на ваше понимание того, что мне следует сохранять нейтралитет по отношению к каждому участнику._

**Comment by mike5555555** [comment]
Здравствуйте, у меня в очередной раз возник вопрос по симулятору. Скажите
пожалуйста, как направлены оси (х, у, z), в начальный момент времени
относительно робота?

вт, 1 дек. 2020 г. в 02:25, Alex Zauzolkov <notifications@github.com>:

**Comment by Zauzolkov** [comment]
> как направлены оси (х, у, z)

Если вы имеете ввиду данные с навигационно-пилотажного датчика, то их можно просматривать в любой момент времени, эта информация отображается в правом верхнем углу окна симулятора. Изначально эти показатели приблизительно равны нулю (при погружении аппарата возникает небольшое отклонение) за исключением глубины, которая меняется сначала резко, а затем плавно.

![2020-12-03_09-01-57_04](https://user-images.githubusercontent.com/50130486/100942193-9c3a9580-3546-11eb-813e-78c2b331997f.png)

Я правильно понял ваш вопрос?

**Comment by mike5555555** [comment]
Не совсем. Я имею ввиду, есть ли какая-то система координат в симуляторе.
Допустим, я нашел какой то объект в координатах, как мне с ориентировать на
него робота. Есть ли какая-то единая система координат в этом бассейне?

чт, 3 дек. 2020 г., 02:16 Alex Zauzolkov <notifications@github.com>:

**Comment by mike5555555** [comment]
Также, если не трудно, можете пожалуйста сказать, в какой системе координат
даны координаты х и y центра объекта в этом видео
https://youtu.be/b3zh1rpElXM на 6 минуте, 15 секунде?

чт, 3 дек. 2020 г. в 08:02, Mike <mikhail.kaminker@gmail.com>:

**Comment by Zauzolkov** [comment]
> Есть ли какая-то единая система координат в этом бассейне

Так понимаю, вы хотите получить текущие координаты робота в бассейне, но это не предусмотрено. Предполагается использование машинного зрения.

> как мне с ориентировать на него робота

Предлагаю вам ознакомится с [видеоуроком 8](https://www.youtube.com/watch?v=odFxWdrtbfE), где рассматривается стабилизация над объектом по изображению.

> в какой системе координат даны координаты х и y центра объекта в этом видео

Это координаты __точки на изображении__ с камеры.

**Comment by mike5555555** [comment]
Здравствуйте, скажите пожалуйста, можно ли где-то купить аппарат для mur
IDE, чтобы его можно было подключить по Wi-Fi?

**Comment by Zauzolkov** [comment]
Пожалуйста, обратитесь к [странице, посвящённой аппарату MiddleAUV](https://robocenter.net/goods/kit/middleauv/). На указанном сайте имеются контакты, по которым следует обращаться с вопросами приобретения.
