### ISSUE TITLE
Соединение программы с симулятором зависает

### ISSUE THREAD

**Issue by nikudaorg** [murproject/mur_simulator#3]
Добрый день! У меня есть проблема: значения, которые приходят в программу через mur api - сильно запаздывают, к примеру изменение yaw доходит до программы только спустя несколько секунд, после того, как поворот произошел. Я посмотрел исходный код murapi и уверен, что проблема не на стороне питона - в нем все выполняется правильно. Судя по всему симулятор с запозданием отправляет данные. При этом, в окне симулятора все нормально, значения меняются сразу же.

**Comment by Zauzolkov** [comment]
Здравствуйте. Уточните, пожалуйста: проблема проявляется, даже когда в скрипте не задействован OpenCV? Попробуйте воспроизвести проблему, используя минимальный скрипт, например:

```python
import time
import pymurapi as mur

auv = mur.mur_init()

if __name__ == '__main__':
    while(True):
        time.sleep(0.05)
        print(auv.get_yaw())
```

Мы сталкивались с подобной проблемой, когда скрипт "не успевал" вовремя обработать данные, будучи сильно загруженным задачами машинного зрения. Также проявления этой проблемы могут варьироваться в зависимости от производительности компьютера.

**Comment by nikudaorg** [comment]
Да, проблема воспроизводится в простейшем скрипте, примерно как у вас. Более того, встроенные примеры, например стабилизации по курсу, также не работает из-,за запаздывающих данных.

**Comment by nikudaorg** [comment]
Производительность ноутбука:
core i7 11 поколения
intel iris xe

**Comment by nikudaorg** [comment]
Кажется помогло добавить 50 миллисекунд задержки на каждой итерации цикла!
