### ISSUE TITLE
Управление роботом в симуляторе

### ISSUE THREAD

**Issue by zheleshk** [murproject/mur_simulator#4]
Здравствуйте, можете подсказать, почему может не работать управление роботом в симуляторе murIDE, программа в local, выбран remote mode, но робот никак не реагирует на клавиатуру. Подскажите, пожалуйста.

**Comment by emily0undrgrnd** [comment]
Здравствуйте, после запуска окна симулятора необходимо нажать на кнопку remote mode, чтобы перейти в режим manual mode. Данный режим предназначен для телеуправления, remote mode необходим для запуска кода. 
Также не забудьте сменить раскладку клавиатуры на английский язык. В симуляторе аппарат реагирует на кнопки W, A, S, D, Q, E, Z, X.
